### ISSUE TITLE
Provide an Official Docker image

### ISSUE THREAD

**Issue by steve-dtg** [dovetail-genomics/dovetail_tools#3]
We should provide a Docker image that contains a prebuilt environment for the latest version of the Omni-C QC workflow. This docker image should be hosted on Dockerhub and we should provide additional instructions in the README.md for how to run given that image.

The Docker image should contain
1. BWA
2. Samtools
3. Samblaster
4. Preseq

Also, I feel as if we should add a regression test to this repository that can go hand-in-hand with new releases and images.

cc @jared-dtg

**Comment by jared-dtg** [comment]
I think that's a great idea. Go for it. Don't merge to master without sign-off though -- since this is public and people are intended to use it, we want to deploy publicly facing changes more carefully than we do with our internal stuff.

Re the regression test, here's one decent data set that can be used: `s3://dtg-jared/lisasBug/*.fastq.gz` Runs in a few minutes, makes sensible numbers. Was the data set used to find & fix issue #2.

Let's make the regression test another ticket though.

**Comment by steve-dtg** [comment]
Sounds good. 

For this repository, I will leave resolutions of PRs completely up to you / commercial.

**Comment by chad388** [comment]
I wanted to check to see if an Omni-C QC docker image is available. I was unable to locate an image on dockerhub. I have been working on installing all of the required software into a docker container, but I ran into some issues when attempting to compile Preseq. I figured that if you already had an image available, I would give that a try.

Thanks,
Chad

**Comment by steve-dtg** [comment]
Hey Chad!

We do not currently have a public image for this repository.

I have had good experiences using [this](https://medium.com/@chadlagore/conda-environments-with-docker-82cdc9d25754) tutorial as a starting point for building Docker images using conda.

**Comment by chad388** [comment]
Thanks steve-dtg. I will try using conda.
